### ISSUE TITLE
Requirements 补充

### ISSUE THREAD

**Issue by SunAriesCN** [AI-OP/edge-brain#1]
补充依赖安装：
CMake 
Bazel 以及相关方法

**Comment by Duan-JM** [comment]
Cmake 依赖安装是指？

**Comment by SunAriesCN** [comment]
https://github.com/ml-gde/e2e-tflite-tutorials/blob/master/CONTRIBUTING.md Global GDEs 开源贡献引导。

**Comment by SunAriesCN** [comment]
已在 readme 体现，关闭 issue。
