### ISSUE TITLE
建议改个库名

### ISSUE THREAD

**Issue by SunAriesCN** [AI-OP/edge-brain#3]
改个库名扩展它的属性，在这里可以集成各种各样的边缘智能算法应用部署，让大家都能投入参与进来。

建议：  
1. edge-ai
2. edge-ml
3. embedded-ai
4. embedded-ml
5. small-brain
6. little-genius
7.

**Comment by Duan-JM** [comment]
咱们叫 Edge-Brain 吧？

**Comment by SunAriesCN** [comment]
It's the really cool name now.
