### ISSUE TITLE
Hope there will be more detailed README.md

### ISSUE THREAD

**Issue by wwdok** [AI-OP/edge-brain#5]
Dear contributors, I am very happy to meet such a valuable project. As a newbie to bazel, I hope that the README.md can include more brief explanations or links, such as what BUILD and WORKSPACE are used for, such as what does `--config elinux_armhf`  mean and is it a fixed writing in this project ? Thanks in advance !

**Comment by Duan-JM** [comment]
Thanks for your time. I will add more detailed very soon. By that time, feel free to explore some official examples [here](https://github.com/bazelbuild/examples) and maybe [this brief tutorial](https://docs.bazel.build/versions/master/guide.html) is good for beginner.

For Chinese player, maybe [this blog](https://blog.csdn.net/elaine_bao/article/details/78668657) is a good start.

**Comment by wwdok** [comment]
Thanks for your sharing, it is helpful !
